// TEMPORARY DATA

export let role = "admin";

export const therapistsData = [
  {
    id: 1,
    therapistId: "2224563890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888240/pexels-photo-2888240.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    specialization: ["Math", "Geometry"],
    languages: ["1B", "2A", "3C"],
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 2,
    therapistId: "2224563890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936225/pexels-photo-936225.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    specialization: ["Physics", "Chemistry"],
    languages: ["5A", "4B", "3C"],
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 3,
    therapistId: "2224563890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    specialization: ["Biology"],
    languages: ["5A", "4B", "3C"],
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 4,
    therapistId: "2224563890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1183365/pexels-photo-1183365.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    specialization: ["History"],
    languages: ["5A", "4B", "3C"],
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 5,
    therapistId: "2224563890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    specialization: ["Music", "History"],
    languages: ["5A", "4B", "3C"],
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 6,
    therapistId: "2224563890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/322422/pexels-photo-322422.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    specialization: ["Physics"],
    languages: ["5A", "4B", "3C"],
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 7,
    therapistId: "2224563890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/2338081/pexels-photo-2338081.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    specialization: ["English", "Spanish"],
    languages: ["5A", "4B", "3C"],
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 8,
    therapistId: "2224563890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    specialization: ["Math", "Geometry"],
    languages: ["5A", "4B", "3C"],
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 9,
    therapistId: "2224563890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    specialization: ["Literature", "English"],
    languages: ["5A", "4B", "3C"],
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 10,
    therapistId: "2224563890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043434/pexels-photo-1043434.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    specialization: ["Biology"],
    languages: ["5A", "4B", "3C"],
    address: "222 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "2224563890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888240/pexels-photo-2888240.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    grade: 5,
    class: "1B",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "2224563890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936225/pexels-photo-936225.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    grade: 5,
    class: "5A",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "2224563890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    grade: 5,
    class: "5A",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "2224563890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1183365/pexels-photo-1183365.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    grade: 5,
    class: "5A",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "2224563890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    grade: 5,
    class: "5A",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "2224563890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/322422/pexels-photo-322422.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    grade: 5,
    class: "5A",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "2224563890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/2338081/pexels-photo-2338081.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    grade: 5,
    class: "5A",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "2224563890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    grade: 5,
    class: "5A",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "2224563890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    grade: 5,
    class: "5A",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "2224563890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043434/pexels-photo-1043434.jpeg?auto=compress&cs=tinysrgb&w=2100",
    phone: "2224563890",
    grade: 5,
    class: "5A",
    address: "222 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "2224563890",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "2224563890",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "2224563890",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "2224563890",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "2224563890",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "2224563890",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "2224563890",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "2224563890",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "2224563890",
    address: "222 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "2224563890",
    address: "222 Main St, Anytown, USA",
  },
];

export const specializationData = [
  {
    id: 1,
    name: "Math",
    therapists: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    therapists: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    therapists: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    therapists: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    therapists: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    therapists: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 3,
    name: "Geography",
    therapists: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    therapists: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    therapists: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    therapists: ["Effie Lynch", "Brett Flowers"],
  },
];

export const languagesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 25,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 3,
    name: "3A",
    capacity: 18,
    grade: 3,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    specialization: "Math",
    class: "1A",
    therapist: "Tommy Wise",
  },
  {
    id: 2,
    specialization: "English",
    class: "2A",
    therapist: "Rhoda Frank",
  },
  {
    id: 3,
    specialization: "Science",
    class: "3A",
    therapist: "Della Dunn",
  },
  {
    id: 4,
    specialization: "Social Studies",
    class: "1B",
    therapist: "Bruce Rodriguez",
  },
  {
    id: 5,
    specialization: "Art",
    class: "4A",
    therapist: "Birdie Butler",
  },
  {
    id: 6,
    specialization: "Music",
    class: "5A",
    therapist: "Bettie Oliver",
  },
  {
    id: 3,
    specialization: "History",
    class: "6A",
    therapist: "Herman Howard",
  },
  {
    id: 8,
    specialization: "Geography",
    class: "6B",
    therapist: "Lucinda Thomas",
  },
  {
    id: 9,
    specialization: "Physics",
    class: "6C",
    therapist: "Ronald Roberts",
  },
  {
    id: 10,
    specialization: "Chemistry",
    class: "4B",
    therapist: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    specialization: "Math",
    class: "1A",
    therapist: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    specialization: "English",
    class: "2A",
    therapist: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    specialization: "Science",
    class: "3A",
    therapist: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    specialization: "Social Studies",
    class: "1B",
    therapist: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    specialization: "Art",
    class: "4A",
    therapist: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    specialization: "Music",
    class: "5A",
    therapist: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 3,
    specialization: "History",
    class: "6A",
    therapist: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    specialization: "Geography",
    class: "6B",
    therapist: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    specialization: "Physics",
    class: "3A",
    therapist: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    specialization: "Chemistry",
    class: "8A",
    therapist: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    specialization: ["Math"],
    class: "1A",
    therapist: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    specialization: ["English"],
    class: "2A",
    therapist: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    specialization: ["Science"],
    class: "3A",
    therapist: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    specialization: ["Social Studies"],
    class: "1B",
    therapist: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    specialization: ["Art"],
    class: "4A",
    therapist: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    specialization: ["Music"],
    class: "5A",
    therapist: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    specialization: ["History"],
    class: "6A",
    therapist: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    specialization: ["Geography"],
    class: "6B",
    therapist: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    specialization: ["Physics"],
    class: "3A",
    therapist: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    specialization: ["Chemistry"],
    class: "8A",
    therapist: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    specialization: "Math",
    class: "1A",
    therapist: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    specialization: "English",
    class: "2A",
    therapist: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    specialization: "Science",
    class: "3A",
    therapist: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    specialization: "Social Studies",
    class: "1B",
    therapist: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    specialization: "Art",
    class: "4A",
    therapist: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    specialization: "Music",
    class: "5A",
    therapist: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    specialization: "History",
    class: "6A",
    therapist: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    specialization: "Geography",
    class: "6B",
    therapist: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    specialization: "Physics",
    class: "3A",
    therapist: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    specialization: "Chemistry",
    class: "8A",
    therapist: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const appointments = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 3, 21, 8, 0),
    end: new Date(2025, 3, 21, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 3, 21, 9, 0),
    end: new Date(2025, 3, 21, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 3, 21, 10, 0),
    end: new Date(2025, 3, 21, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 3, 21, 11, 0),
    end: new Date(2025, 3, 21, 11, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 3, 22, 9, 0),
    end: new Date(2025, 3, 22, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 3, 22, 10, 0),
    end: new Date(2025, 3, 22, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 3, 22, 11, 0),
    end: new Date(2025, 3, 22, 11, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 3, 23, 8, 0),
    end: new Date(2025, 3, 23, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 3, 23, 10, 0),
    end: new Date(2025, 3, 23, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 3, 23, 11, 0),
    end: new Date(2025, 3, 23, 11, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 3, 24, 9, 0),
    end: new Date(2025, 3, 24, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 3, 24, 10, 0),
    end: new Date(2025, 3, 24, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 3, 24, 11, 0),
    end: new Date(2025, 3, 24, 11, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 3, 25, 8, 0),
    end: new Date(2025, 3, 25, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 3, 25, 9, 0),
    end: new Date(2025, 3, 25, 9, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 3, 25, 11, 0),
    end: new Date(2025, 3, 25, 11, 45),
  },
];